/* Generated By:JavaCC: Do not edit this line. DotGParserConstants.java */
package org.workcraft.plugins.stg.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface DotGParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINEBREAK = 4;
  /** RegularExpression Id. */
  int INPUT_HEADER = 5;
  /** RegularExpression Id. */
  int OUTPUT_HEADER = 6;
  /** RegularExpression Id. */
  int INTERNAL_HEADER = 7;
  /** RegularExpression Id. */
  int DUMMY_HEADER = 8;
  /** RegularExpression Id. */
  int GRAPH = 9;
  /** RegularExpression Id. */
  int MARKING = 10;
  /** RegularExpression Id. */
  int CAPACITY = 11;
  /** RegularExpression Id. */
  int UNSUPPORTED_HEADER = 12;
  /** RegularExpression Id. */
  int NAME = 13;
  /** RegularExpression Id. */
  int DIRECTION = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int ANY = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<LINEBREAK>",
    "\".inputs\"",
    "\".outputs\"",
    "\".internal\"",
    "\".dummy\"",
    "\".graph\"",
    "\".marking\"",
    "\".capacity\"",
    "<UNSUPPORTED_HEADER>",
    "<NAME>",
    "<DIRECTION>",
    "<INTEGER>",
    "\"{\"",
    "\"}\"",
    "\"<\"",
    "\">\"",
    "\",\"",
    "\"/\"",
    "\"=\"",
    "<ANY>",
  };

}
