/* Generated By:JavaCC: Do not edit this line. BooleanParserConstants.java */
package org.workcraft.plugins.cpog.optimisation.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface BooleanParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUALS = 5;
  /** RegularExpression Id. */
  int NOTEQUALS = 6;
  /** RegularExpression Id. */
  int IMPLIES = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int XOR = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int POSTNOT = 12;
  /** RegularExpression Id. */
  int CONSTANT = 13;
  /** RegularExpression Id. */
  int VARIABLE = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<EQUALS>",
    "<NOTEQUALS>",
    "<IMPLIES>",
    "<OR>",
    "<XOR>",
    "<AND>",
    "<NOT>",
    "\"\\\'\"",
    "<CONSTANT>",
    "<VARIABLE>",
    "\"(\"",
    "\")\"",
  };

}
