plugins {
    id 'java'
    id 'org.javacc.javacc'
    id 'com.github.kt3k.coveralls'
    id 'org.danilopianini.cpd'
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = gradle.javaSourceVersion
    targetCompatibility = gradle.javaTargetVersion
}

subprojects {
    repositories {
        mavenCentral()
    }

    apply plugin: 'java'

    sourceSets {
        main.java.srcDirs = ['src', 'src-gen']
        main.resources.srcDirs = ['res']
        test.java.srcDirs = ['test-src']
        test.resources.srcDirs = ['test-res']
    }

    compileJava {
        options.encoding = 'UTF-8'
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        if (JavaVersion.current().isJava9Compatible()) {
            options.release = gradle.javaReleaseVersion
        }
    }

    apply plugin: 'org.javacc.javacc'

    compileJavacc {
        inputDirectory = file('javacc')
        outputDirectory = file('src-gen')
        include '**/*.jj'
        arguments = [grammar_encoding: 'UTF-8', static: 'false']
    }

    tasks.register('cleanJavacc', Delete) {
        delete compileJavacc.outputDirectory
    }


    apply plugin: 'java-library'

    configurations {
        lib
    }

    dependencies {
        lib fileTree(dir: gradle.libDir, include: ['**/*.jar'])
        configurations.api.extendsFrom(configurations.lib)
        testImplementation gradle.junit as String
        testRuntimeOnly gradle.junitPlatformLauncher as String
        javacc gradle.javacc as String
    }


    test {
        useJUnitPlatform()
        workingDir = rootDir
        testLogging {
            events "failed"
            exceptionFormat = "full"
            // Uncomment the next two lines to show stdout and stderr of tests
            /*  outputs.upToDateWhen {false} */
            /*  showStandardStreams = true */
        }
    }


    apply plugin: 'checkstyle'

    checkstyle {
        toolVersion = gradle.checkstyleVersion
        configFile = file("${project.rootDir}/config/checkstyle/checkstyle.xml")
    }

    tasks.withType(Checkstyle).configureEach {
        group = 'Verification'
    }

    tasks.named('checkstyleMain') {
        exclude gradle.javaccExclude
    }

    tasks.register('checkstyle') {
        group = 'Verification'
        description = 'Run Checkstyle analysis for all sources'
        dependsOn tasks.withType(Checkstyle)
    }


    apply plugin: 'pmd'

    pmd {
        toolVersion = gradle.pmdVersion
        consoleOutput = true
        incrementalAnalysis = true
        ruleSetFiles = files("${project.rootDir}/config/pmd/rules.xml")
        ruleSets = []
    }

    tasks.named('pmdMain') {
        exclude gradle.javaccExclude
    }

    tasks.withType(Pmd).configureEach {
        group = 'Verification'
        classpath += files("${System.getProperty('java.home')}/lib/jrt-fs.jar")
    }

    tasks.register('pmd') {
        group = 'Verification'
        description = 'Run PMD analysis for all sources'
        dependsOn tasks.withType(Pmd)
    }


    apply plugin: 'org.danilopianini.cpd'

    cpd {
        toolVersion = gradle.pmdVersion
        minimumTokenCount = 250
    }

    cpdCheck {
        group = 'Verification'
        dependsOn compileJavacc
        source = sourceSets.main.allJava
        exclude gradle.javaccExclude
    }


    apply plugin: 'jacoco'

    jacoco {
        toolVersion = gradle.jacocoVersion
    }

    jacocoTestReport {
        reports {
            xml.required = true    /* XML report for coveralls */
            html.required = false  /* skip human readable report */
        }
    }

    afterEvaluate {
        tasks.register('copyLibs', Copy) {
            from configurations.lib
            into layout.buildDirectory.dir(gradle.libDir as String)
            include '*.jar'
        }

        jar {
            dependsOn copyLibs
            destinationDirectory = layout.buildDirectory.dir('bin')
            manifest {
                attributes 'Class-Path': provider {
                    configurations.lib.collect { "../$gradle.libDir/" + it.name }.join(' ')
                }
            }
        }
    }


    apply plugin: 'eclipse'

    eclipse {
        classpath {
            defaultOutputDir = file('build/eclipse/bin/')
            file.whenMerged {
                entries.each {
                    if (it.kind == 'src' && it.hasProperty('output')) {
                        it.output = it.output.replace('bin/', 'build/eclipse/')
                    }
                }
            }
        }
    }

    tasks.named('eclipseClasspath') {
        dependsOn 'compileJavacc'
    }


    apply plugin: 'idea'

    idea.module {
        sourceDirs = [file('src'), file('javacc'), file('src-gen')]
        generatedSourceDirs = [file('src-gen')]
        resourceDirs = [file('res'), file('models')]
        excludeDirs = [file('.gradle'), file('.settings'), file('bin'), file('build'), file('gradle')]
        inheritOutputDirs = false
        outputDir = file('build/idea/')
        testSources.setFrom(file('test-src'))
        testResources.setFrom(file('test-res'))
    }

    tasks.named('ideaModule') {
        dependsOn 'compileJavacc'
    }

    tasks.register('cleanAll') {
        group = 'Build'
        dependsOn 'clean', 'cleanEclipse', 'cleanIdea', 'cleanJavacc'
    }
}


apply plugin: 'java'

cpdCheck {
    group = 'Verification'
    dependsOn compileJavacc
    source = sourceSets.main.allJava
    exclude gradle.javaccExclude
}


apply plugin: 'jacoco'

jacoco {
    toolVersion = gradle.jacocoVersion
}

def coverageProjects = subprojects.findAll {
    it.name ==~ ~(gradle.coverageProjects.join('|'))
}

evaluationDependsOnChildren()

tasks.register('jacocoRootReport', JacocoReport) {
    dependsOn(coverageProjects.test)

    sourceDirectories.from = coverageProjects.sourceSets.main.allSource.srcDirs
    additionalSourceDirs.from = coverageProjects.sourceSets.main.allSource.srcDirs
    classDirectories.from = coverageProjects.sourceSets.main.output
    executionData.from = coverageProjects.jacocoTestReport.executionData

    reports {
        xml.required = true   // XML report for coveralls
        html.required = true  // human readable report
    }
}

afterEvaluate {
    def jacocoExclude = [gradle.javaccExclude]
    subprojects {
        if (it.hasProperty('excludeFromCoverage')) {
            jacocoExclude += it.excludeFromCoverage
        }
    }
    tasks.named('jacocoRootReport').configure {
        classDirectories.from = classDirectories.files.collect {
            fileTree(dir: it, exclude: jacocoExclude)
        }
        doLast {
            println 'Excluding from coverage:'
            jacocoExclude.each { println "  - " + it }
        }
    }
}

coveralls {
    sourceDirs = coverageProjects.sourceSets.main.allSource.srcDirs.flatten()
    jacocoReportPath = layout.buildDirectory.file('reports/jacoco/jacocoRootReport/jacocoRootReport.xml').get().asFile.path
}

tasks.coveralls {
    group = 'Verification'
    description = 'Generate coverage report for all subprojects with tests.'
    dependsOn jacocoRootReport
}


apply plugin: 'idea'

idea.module {
    excludeDirs = [file('.gradle'), file('config'), file('dist-template'), file('doc'), file('gradle')]
    outputDir = file('build/idea/')
}

def workcraftRunConfigurationFile = file('.idea/runConfigurations/Workcraft.xml')

def workcraftRunConfiguration = '''<component name="ProjectRunConfigurationManager">
    <configuration default="false" name="Workcraft" type="Application" factoryName="Application" singleton="true">
        <option name="MAIN_CLASS_NAME" value="org.workcraft.Console" />
        <option name="WORKING_DIRECTORY" value="file://$PROJECT_DIR$" />
        <module name="WorkcraftRunner" />
        <method v="2" />
    </configuration>
</component>
'''

tasks.register('ideaRunConfiguration') {
    group = 'Build Setup'
    description = 'Generate IntelliJ run configuration for Workcraft.'
    doLast {
        workcraftRunConfigurationFile.parentFile.mkdirs()
        workcraftRunConfigurationFile.text = workcraftRunConfiguration
    }
}

tasks.register('cleanAll') {
    group = 'Build'
    description = 'Deletes build directory and generated source files.'
    doLast {
        delete workcraftRunConfigurationFile
    }
}

tasks.cleanAll.doLast {
    delete 'build/'  // Remove root build directory (left untouched by other clean tasks)
}

allprojects {
    javadoc.group = null  // Exclude javadoc from the list of tasks
    jar.group = null      // Exclude jar from the list of tasks
}
