#!/bin/sh

# Remember the current working directory
CURRENT_DIR="$PWD"

# Change to Workcraft directory
cd "$(dirname "$0")"

# Check that Workcraft is built
if [ ! -f WorkcraftCore/build/libs/WorkcraftCore.jar ]; then
    echo "WorkcraftCore.jar not found. Build Workcraft with './gradlew assemble' first." >&2
    exit 1
fi

# Run Workcraft with classpath for all plugins
export CLASSPATH="$(ls -1 */build/libs/*.jar | tr '\n' ':')"

java org.workcraft.Console -dir:"$CURRENT_DIR" "$@"
