#!/bin/sh -e

# Remember the current working directory
CURRENT_DIR="$PWD"

# Change to Workcraft home directory and put it into the WORKCRAFT_HOME variable
cd "$(dirname "$0")"
WORKCRAFT_HOME="$PWD"

# Set the JVM executable in JAVA_BIN variable (if not defined yet)
if [ -z "$JAVA_BIN" ]; then
    if [ -z "$JAVA_HOME" ]; then
        JAVA_BIN=java
    else
        if [ -e "$JAVA_HOME/bin/java" ]; then
            JAVA_BIN="$JAVA_HOME/bin/java"
        else
            JAVA_BIN="$JAVA_HOME/java"
        fi
    fi
fi

export CLASSPATH="$WORKCRAFT_HOME/workcraft.jar:$WORKCRAFT_HOME/plugins/*"

"$JAVA_BIN" org.workcraft.Console -dir:"$CURRENT_DIR" "$@"
