/* Generated By:JavaCC: Do not edit this line. CpogExpressionParserConstants.java */
package org.workcraft.plugins.cpog.expressions.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CpogExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OVERLAY = 5;
  /** RegularExpression Id. */
  int SEQUENCE = 6;
  /** RegularExpression Id. */
  int VARIABLE = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"->\"",
    "<VARIABLE>",
    "\"(\"",
    "\")\"",
  };

}
