/* Generated By:JavaCC: Do not edit this line. DotGParserConstants.java */
package org.workcraft.plugins.stg.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DotGParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int REST = 4;
  /** RegularExpression Id. */
  int ANY = 5;
  /** RegularExpression Id. */
  int LINEBREAK = 6;
  /** RegularExpression Id. */
  int INPUT_HEADER = 7;
  /** RegularExpression Id. */
  int OUTPUT_HEADER = 8;
  /** RegularExpression Id. */
  int INTERNAL_HEADER = 9;
  /** RegularExpression Id. */
  int DUMMY_HEADER = 10;
  /** RegularExpression Id. */
  int GRAPH = 11;
  /** RegularExpression Id. */
  int MARKING = 12;
  /** RegularExpression Id. */
  int CAPACITY = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int UNSUPPORTED_HEADER = 15;
  /** RegularExpression Id. */
  int NAME = 16;
  /** RegularExpression Id. */
  int DIRECTION = 17;
  /** RegularExpression Id. */
  int INTEGER = 18;

  /** Lexical state. */
  int IGNORE_ALL = 0;
  /** Lexical state. */
  int IGNORE_LINE = 1;
  /** Lexical state. */
  int DEFAULT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<REST>",
    "<ANY>",
    "<LINEBREAK>",
    "\".inputs\"",
    "\".outputs\"",
    "\".internal\"",
    "\".dummy\"",
    "\".graph\"",
    "\".marking\"",
    "\".capacity\"",
    "\".end\"",
    "<UNSUPPORTED_HEADER>",
    "<NAME>",
    "<DIRECTION>",
    "<INTEGER>",
    "\"{\"",
    "\"}\"",
    "\"<\"",
    "\">\"",
    "\",\"",
    "\"/\"",
    "\"=\"",
  };

}
