/* Generated By:JavaCC: Do not edit this line. BreezeParserConstants.java */
package org.workcraft.parsers.breeze.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface BreezeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRIMITIVE_PART = 6;
  /** RegularExpression Id. */
  int ZERO = 7;
  /** RegularExpression Id. */
  int VARIABLE_ARRAY_TYPE = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int ACTIVE = 10;
  /** RegularExpression Id. */
  int PASSIVE = 11;
  /** RegularExpression Id. */
  int INPUT = 12;
  /** RegularExpression Id. */
  int INP = 13;
  /** RegularExpression Id. */
  int OUTPUT = 14;
  /** RegularExpression Id. */
  int NAMED_TYPE = 15;
  /** RegularExpression Id. */
  int NUMERIC_TYPE = 16;
  /** RegularExpression Id. */
  int BOOL_FALSE = 17;
  /** RegularExpression Id. */
  int PARAMETERS = 18;
  /** RegularExpression Id. */
  int PARAM = 19;
  /** RegularExpression Id. */
  int PORTS = 20;
  /** RegularExpression Id. */
  int PORT = 21;
  /** RegularExpression Id. */
  int SYNC_PORT = 22;
  /** RegularExpression Id. */
  int ARRAYED_PORT = 23;
  /** RegularExpression Id. */
  int ARRAYED_SYNC_PORT = 24;
  /** RegularExpression Id. */
  int SYMBOL = 25;
  /** RegularExpression Id. */
  int CENTER_STRING = 26;
  /** RegularExpression Id. */
  int IMPLEMENTATION = 27;
  /** RegularExpression Id. */
  int TYPE_STRING = 28;
  /** RegularExpression Id. */
  int TYPE_CARDINAL = 29;
  /** RegularExpression Id. */
  int TYPE_BOOLEAN = 30;
  /** RegularExpression Id. */
  int CASE = 31;
  /** RegularExpression Id. */
  int ELSE = 32;
  /** RegularExpression Id. */
  int STRING_APPEND = 33;
  /** RegularExpression Id. */
  int NUMBER_TO_STRING = 34;
  /** RegularExpression Id. */
  int PLUS = 35;
  /** RegularExpression Id. */
  int SYNC = 36;
  /** RegularExpression Id. */
  int PUSH = 37;
  /** RegularExpression Id. */
  int PULL = 38;
  /** RegularExpression Id. */
  int CHANNELS = 39;
  /** RegularExpression Id. */
  int ATTRIBUTES = 40;
  /** RegularExpression Id. */
  int COMPONENTS = 41;
  /** RegularExpression Id. */
  int COMPONENT = 42;
  /** RegularExpression Id. */
  int BREEZE_PART = 43;
  /** RegularExpression Id. */
  int TYPE = 44;
  /** RegularExpression Id. */
  int IMPORT = 45;
  /** RegularExpression Id. */
  int OBR = 46;
  /** RegularExpression Id. */
  int CBR = 47;
  /** RegularExpression Id. */
  int QUOTED_VALUE = 48;
  /** RegularExpression Id. */
  int VALUE = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"primitive-part\"",
    "\"0\"",
    "\"variable-array-type\"",
    "<INTEGER>",
    "\"active\"",
    "\"passive\"",
    "\"input\"",
    "\"inp\"",
    "\"output\"",
    "\"named-type\"",
    "\"numeric-type\"",
    "\"#f\"",
    "\"parameters\"",
    "\"param\"",
    "\"ports\"",
    "\"port\"",
    "\"sync-port\"",
    "\"arrayed-port\"",
    "\"arrayed-sync-port\"",
    "\"symbol\"",
    "\"centre-string\"",
    "\"implementation\"",
    "\"string\"",
    "\"\\\"cardinal\\\"\"",
    "\"\\\"boolean\\\"\"",
    "\"case\"",
    "\"else\"",
    "\"string-append\"",
    "\"number->string\"",
    "\"+\"",
    "\"sync\"",
    "\"push\"",
    "\"pull\"",
    "\"channels\"",
    "\"attributes\"",
    "\"components\"",
    "\"component\"",
    "\"breeze-part\"",
    "\"type\"",
    "\"import\"",
    "\"(\"",
    "\")\"",
    "<QUOTED_VALUE>",
    "<VALUE>",
  };

}
