# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.7
.model Untitled
.inputs csc0.in
.outputs csc0.out1 csc0.out2
.graph
csc0.in+ csc0.out1+
csc0.in+/1 csc0.out2+
csc0.in- csc0.out2-
csc0.in-/1 csc0.out1-
csc0.out1+ csc0.in-/1
csc0.out1- csc0.in+/1
csc0.out2+ csc0.in-
csc0.out2- csc0.in+
.marking {<csc0.out2-,csc0.in+>}
.end
