/* Generated By:JavaCC: Do not edit this line. VerilogParser.java */
package org.workcraft.plugins.circuit.javacc;

import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.LinkedList;

import org.workcraft.dom.Node;
import org.workcraft.util.Pair;
import org.workcraft.util.Triple;
import org.workcraft.exceptions.InvalidConnectionException;
import org.workcraft.exceptions.FormatException;
import org.workcraft.exceptions.NotFoundException;

public class VerilogParser implements VerilogParserConstants {

    public class Module {
        public final String name;
        public final List<Port> ports;
        public final List<Instance> instances;
        public Module(String name, List<Port> ports, List<Instance> instances) {
            this.name = name;
            this.ports = ports;
            this.instances = instances;
        }
    }

    public class Port {
        public final String name;
        public final String type;
        public Port(String name, String type) {
            this.name = name;
            this.type = type;
        }
    }



    public class Instance {
        public final String name;
        public final String moduleName;
        public final List<Connection> connections;
        public Instance(String name, String moduleName, List<Connection> connections) {
            this.name = name;
            this.moduleName = moduleName;
            this.connections = connections;
        }
    }

    public class Connection {
        public final String name;
        public final String netName;
        public Connection(String name, String netName) {
            this.name = name;
            this.netName = netName;
        }
    }

  final public List<Module> parseCircuit() throws ParseException {
    List<Module> modules;
    modules = parseModules();
        {if (true) return modules;}
    throw new Error("Missing return statement in function");
  }

  final public List<Module> parseModules() throws ParseException {
    Module module;
    List<Module> modules = new LinkedList<Module>();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MODULE:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      module = parseModule();
            modules.add(module);
    }
        {if (true) return modules;}
    throw new Error("Missing return statement in function");
  }

  final public Module parseModule() throws ParseException {
    Token name;
    List<Port> ports;
    List<Instance> instances;
    jj_consume_token(MODULE);
    name = jj_consume_token(NAME);
    ports = parsePorts();
    instances = parseInstances();
    jj_consume_token(ENDMODULE);
        {if (true) return new Module(name.image, ports, instances);}
    throw new Error("Missing return statement in function");
  }

  final public List<Port> parsePorts() throws ParseException {
    List<Port> ports;
    if (jj_2_1(2147483647)) {
      ports = parseCompactPorts();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 24:
      case 29:
        ports = parseComplexPorts();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
        {if (true) return ports;}
    throw new Error("Missing return statement in function");
  }

  final public List<Port> parseCompactPorts() throws ParseException {
    Port port;
    List<Port> ports = new LinkedList<Port>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 24:
      jj_consume_token(24);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INPUT:
        case OUTPUT:
        case INOUT:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
        port = parseCompactPort();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 28:
          jj_consume_token(28);
          break;
        default:
          jj_la1[3] = jj_gen;
          ;
        }
                        ports.add(port);
      }
      jj_consume_token(25);
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    jj_consume_token(29);
        {if (true) return ports;}
    throw new Error("Missing return statement in function");
  }

  final public Port parseCompactPort() throws ParseException {
    Token nameToken;
    Token typeToken;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INPUT:
      typeToken = jj_consume_token(INPUT);
      break;
    case OUTPUT:
      typeToken = jj_consume_token(OUTPUT);
      break;
    case INOUT:
      typeToken = jj_consume_token(INOUT);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    nameToken = jj_consume_token(NAME);
        String name = nameToken.image;
        String type = typeToken.image;
        {if (true) return new Port(name, type);}
    throw new Error("Missing return statement in function");
  }

  final public List<Port> parseComplexPorts() throws ParseException {
    List<String> declarations;
    List<Port> definitions;
    declarations = parsePortsDeclaration();
    definitions = parsePortsDefinitions();
        HashMap<String, String> nameToType = new HashMap<String, String>();
        for (Port port: definitions) {
                nameToType.put(port.name, port.type);
        }
        List<Port> ports = new LinkedList<Port>();
                for (String name: declarations) {
                        String type = nameToType.get(name);
                ports.add(new Port(name, type));
        }
        {if (true) return ports;}
    throw new Error("Missing return statement in function");
  }

  final public List<String> parsePortsDeclaration() throws ParseException {
    List<String> names = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 24:
      jj_consume_token(24);
      names = parseNames();
      jj_consume_token(25);
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(29);
                List<String> ports = new LinkedList<String>();
                if (names != null) {
                        ports.addAll(names);
                }
                {if (true) return ports;}
    throw new Error("Missing return statement in function");
  }

  final public List<Port> parsePortsDefinitions() throws ParseException {
    List<Port> ports;
    List<Port> allPorts = new LinkedList<Port>();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INPUT:
      case OUTPUT:
      case INOUT:
      case REG:
      case WIRE:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      ports = parsePortsDefinition();
                allPorts.addAll(ports);
    }
        {if (true) return allPorts;}
    throw new Error("Missing return statement in function");
  }

  final public List<Port> parsePortsDefinition() throws ParseException {
    List<String> names = new LinkedList<String>();
    Token typeToken;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INPUT:
      typeToken = jj_consume_token(INPUT);
      break;
    case OUTPUT:
      typeToken = jj_consume_token(OUTPUT);
      break;
    case INOUT:
      typeToken = jj_consume_token(INOUT);
      break;
    case REG:
      typeToken = jj_consume_token(REG);
      break;
    case WIRE:
      typeToken = jj_consume_token(WIRE);
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    names = parseNames();
    jj_consume_token(29);
        String type = typeToken.image;
        List<Port> ports = new LinkedList<Port>();
        for (String name: names) {
                Port port = new Port(name, type);
                ports.add(port);
        }
        {if (true) return ports;}
    throw new Error("Missing return statement in function");
  }

  final public List<String> parseNames() throws ParseException {
    Token nameToken;
    List<String> names = new LinkedList<String>();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NAME:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      nameToken = jj_consume_token(NAME);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 28:
        jj_consume_token(28);
        break;
      default:
        jj_la1[10] = jj_gen;
        ;
      }
                String name = nameToken.image;
            names.add(name);
    }
        {if (true) return names;}
    throw new Error("Missing return statement in function");
  }

  final public List<Instance> parseInstances() throws ParseException {
    Instance instance;
    List<Instance> instances = new LinkedList<Instance>();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NAME:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_5;
      }
      instance = parseInstance();
            instances.add(instance);
    }
        {if (true) return instances;}
    throw new Error("Missing return statement in function");
  }

  final public Instance parseInstance() throws ParseException {
    Token moduleNameToken;
    Token nameToken = null;
    List<String> parameters;
    List<Connection> connections;
    moduleNameToken = jj_consume_token(NAME);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      nameToken = jj_consume_token(NAME);
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
    label_6:
    while (true) {
      jj_consume_token(24);
      connections = parseConnections();
      jj_consume_token(25);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 24:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_6;
      }
    }
    jj_consume_token(29);
        String moduleName = moduleNameToken.image;
        String name = (nameToken == null ? null : nameToken.image);
        {if (true) return new Instance(name, moduleName, connections);}
    throw new Error("Missing return statement in function");
  }

  final public List<Connection> parseConnections() throws ParseException {
    List<Connection> connections;
    if (jj_2_2(2147483647)) {
      connections = parseNamedConnections();
    } else {
      connections = parseOrderedConnections();
    }
        {if (true) return connections;}
    throw new Error("Missing return statement in function");
  }

  final public List<Connection> parseNamedConnections() throws ParseException {
    Connection connection;
    List<Connection> connections = new LinkedList<Connection>();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 30:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_7;
      }
      connection = parseNamedConnection();
            connections.add(connection);
    }
        {if (true) return connections;}
    throw new Error("Missing return statement in function");
  }

  final public Connection parseNamedConnection() throws ParseException {
    Token portName;
    Token netName;
    jj_consume_token(30);
    portName = jj_consume_token(NAME);
    jj_consume_token(24);
    netName = jj_consume_token(NAME);
    jj_consume_token(25);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 28:
      jj_consume_token(28);
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
        {if (true) return new Connection(portName.image, netName.image);}
    throw new Error("Missing return statement in function");
  }

  final public List<Connection> parseOrderedConnections() throws ParseException {
    List<String> wires;
    List<Connection> connections = new LinkedList<Connection>();
    wires = parseNames();
        for (String wire: wires) {
                Connection connection = new Connection(null, wire);
                connections.add(connection);
        }
        {if (true) return connections;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_3R_9() {
    if (jj_scan_token(30)) return true;
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(24)) return true;
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(25)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_3R_12()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_8() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_10()) jj_scanpos = xsp;
    if (jj_scan_token(29)) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(24)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_11()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(25)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) return true;
    }
    }
    if (jj_scan_token(NAME)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_8()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public VerilogParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[16];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2000,0x21000000,0x38000,0x10000000,0x1000000,0x38000,0x1000000,0xf8000,0xf8000,0x100000,0x10000000,0x100000,0x100000,0x1000000,0x40000000,0x10000000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public VerilogParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public VerilogParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new VerilogParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public VerilogParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new VerilogParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public VerilogParser(VerilogParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(VerilogParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[31];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 16; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 31; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 2; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
