helpRegex("check.*", "checkHelp.txt");
helpRegex("convert.*", "convertHelp.txt");
helpRegex("export.*", "exportHelp.txt");
helpRegex("import.*", "importHelp.txt");
helpRegex("insert.*", "insertHelp.txt");
helpRegex("layout.*", "layoutHelp.txt");
helpRegex("stat.*", "statHelp.txt");
helpRegex("resolve.*", "resolveHelp.txt");
helpRegex("synth.*", "synthHelp.txt");
helpRegex("tag.*", "tagHelp.txt");
helpRegex("transform.*", "transformHelp.txt");
exit();
